export const pageFetchingHeaders = {
  // eslint-disable-next-line prettier/prettier
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'Accept-Language': 'en-US,en;q=0.9',
  'Accept-Encoding': 'gzip, deflate, br',
  // eslint-disable-next-line prettier/prettier
  'Connection': 'keep-alive',
  'Upgrade-Insecure-Requests': '1',
};

export const PagesPaths = {
  Home: '/',
  Ministers: '/ministers',
  Broadcasts: '/broadcasts',
  Sermons: '/media/sermons',
  Contacts: '/contact-us',
  GetInTouch: '/get-in-touch',
  Blog: '/blog',
  BlogAuthor: '/blog/author',
  AboutUs: '/about-us',
  Giving: '/giving',
  LiveStreams: '/media/live-streams',
  Terms: '/terms',
  PrivacyPolicy: '/privacy',
  PrayerRequest: '/prayer-request',
  GospelPage: '/gospel',
  Resources: '/resources',
  OurBeliefs: '/our-beliefs',
  Staff: '/staff',
  UpcomingEvents: '/upcoming-events',
  SuccessSubscription: '/success-subscription',
  Ministries: '/ministries',
  KidsMinistry: '/ministries/kids',
  YouthMinistry: '/ministries/youth',
  WorshipMinistry: '/ministries/worship',
  FamilyMinistry: '/ministries/family',
  MissionaryMinistry: '/ministries/missionary',
  SmallGroupsMinistry: '/ministries/small-groups',
  WomenMinistry: '/ministries/women',
  Participation: '/participation',
  Timeline: '/timeline',
  Media: '/media',
  OurPlans: '/our-plans',
  Phones: '/phones',
  SpiritualLife: '/spiritual-life',
  PastorsBlog: '/blog',
  Baptism: '/spiritual-life/baptism',
  Marriage: '/spiritual-life/marriage',
  NotFoundPage: '/404',
};
