export const pageFetchingHeaders = {
  accept: 'application/json',
  'content-type': 'application/json',
  origin: 'https://www.volunteermatch.org',
  referer: 'https://www.volunteermatch.org/search',
  'user-agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
};

export const PagesPaths = {
  Home: '/',
  Ministers: '/ministers',
  Broadcasts: '/broadcasts',
  Sermons: '/media/sermons',
  Contacts: '/contact-us',
  GetInTouch: '/get-in-touch',
  Blog: '/blog',
  BlogAuthor: '/blog/author',
  AboutUs: '/about-us',
  Giving: '/giving',
  LiveStreams: '/media/live-streams',
  Terms: '/terms',
  PrivacyPolicy: '/privacy',
  PrayerRequest: '/prayer-request',
  GospelPage: '/gospel',
  Resources: '/resources',
  OurBeliefs: '/our-beliefs',
  Staff: '/staff',
  UpcomingEvents: '/upcoming-events',
  SuccessSubscription: '/success-subscription',
  Ministries: '/ministries',
  KidsMinistry: '/ministries/kids',
  YouthMinistry: '/ministries/youth',
  WorshipMinistry: '/ministries/worship',
  FamilyMinistry: '/ministries/family',
  MissionaryMinistry: '/ministries/missionary',
  SmallGroupsMinistry: '/ministries/small-groups',
  WomenMinistry: '/ministries/women',
  Participation: '/participation',
  Timeline: '/timeline',
  Media: '/media',
  OurPlans: '/our-plans',
  Phones: '/phones',
  SpiritualLife: '/spiritual-life',
  PastorsBlog: '/blog',
  Baptism: '/spiritual-life/baptism',
  Marriage: '/spiritual-life/marriage',
  NotFoundPage: '/404',
};
