export const GutenbergBlocksTypes = {
  paragraph: 'p',
  image: 'image',
  heading: 'heading',
  gallery: 'gallery',
  file: 'file',
  audio: 'audio',
  video: 'video',
  quote: 'quote',
  list: 'list',
  listItem: 'list-item',
  code: 'code',
  preformatted: 'preformatted',
  verse: 'verse',
  separator: 'hr',
  cite: 'cite',
};
