export const RoutePath = {
  Home: "/",
  Ministers: "/ministers",
  Broadcasts: "/broadcasts",
  Sermons: "/sermons",
  ContactUs: "/contact-us",
  Blog: "/blog",
  AboutUs: "/about-us",
  Giving: "/giving",
  LiveStreams: "/live-streams",
  Terms: "/terms",
  PrivacyPolicy: "/privacy",
  PrayerRequest: "/prayer-request",
  GospelPage: "/gospel",
  Resources: "/resources",
  OurBeliefs: "/our-beliefs",
  Staff: "/staff",
  UpcomingEvents: "/upcoming-events",
};
