import { PagesSlugs } from './PagesSlugs';

export const RoutePath = {
  Home: '/',
  // Ministers: '/ministers',
  // Broadcasts: '/broadcasts',
  Sermons: `/media/${PagesSlugs.Sermons.en}`,
  Contacts: `/${PagesSlugs.Contacts.en}`,
  // GetInTouch: '/get-in-touch',
  Blog: `/${PagesSlugs.PastorsBlog.en}`,
  BlogAuthor: `/${PagesSlugs.PastorsBlog.en}/author`,
  AboutUs: `/${PagesSlugs.AboutUs.en}`,
  Giving: `/${PagesSlugs.Giving.en}`,
  LiveStreams: `/media/${PagesSlugs.LiveStreams.en}`,
  Terms: `/${PagesSlugs.Terms.en}`,
  PrivacyPolicy: `/${PagesSlugs.PrivacyPolicy.en}`,
  // PrayerRequest: '/prayer-request',
  // GospelPage: '/gospel',
  // Resources: '/resources',
  // OurBeliefs: '/our-beliefs',
  Staff: `/${PagesSlugs.Staff.en}`,
  UpcomingEvents: `/${PagesSlugs.UpcomingEvents.en}`,
  // SuccessSubscription: '/success-subscription',
  Ministries: '/ministries',
  KidsMinistry: `/ministries/${PagesSlugs.KidsMinistry.en}`,
  YouthMinistry: `/ministries/${PagesSlugs.YouthMinistry.en}`,
  WorshipMinistry: `/ministries/${PagesSlugs.WorshipMinistry.en}`,
  FamilyMinistry: `/ministries/${PagesSlugs.FamilyMinistry.en}`,
  MissionaryMinistry: `/ministries/${PagesSlugs.MissionaryMinistry.en}`,
  SmallGroupsMinistry: `/ministries/${PagesSlugs.SmallGroupsMinistry.en}`,
  WomenMinistry: `/ministries/${PagesSlugs.WomenMinistry.en}`,
  // Participation: '/participation',
  Timeline: '/timeline',
  Media: '/media',
  // OurPlans: '/our-plans',
  // Phones: '/phones',
  // SpiritualLife: '/spiritual-life',
  PastorsBlog: `/${PagesSlugs.PastorsBlog.en}`,
  // Baptism: '/spiritual-life/baptism',
  // Marriage: '/spiritual-life/marriage',
  NotFoundPage: '/404',
};
