import Head from "next/head";
import dynamic from "next/dynamic";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Container from "@/ui/containers/Container/Container";
import MarkdownContent from "@/ui/components/MarkdownContent/MarkdownContent";
import { Text } from "@/ui/components/ui-kit";
import RestApiService from "../services/RestApi";
import useTranslationFunction from "@/hooks/useTranslationFunction";
import { PagesIDs } from "@/constants";

import styles from "../styles/pages/giving.module.scss";

const DynamicDonationForm = dynamic(
  () => import("@/ui/components/page-specific/giving/DonationForm/DonationForm")
);

export default function Giving({ data }: any) {
  const translate = useTranslationFunction();
  console.log(data.contentData);

  return (
    <>
      <Head>
        <title>{translate("site_name")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logofavicon.svg" />
      </Head>
      <div className={styles.giving}>
        <Container isMarkdownContent={true}>
          <Text textType="h1" className={styles.giving__title}>
            {data.titleData}
          </Text>

          <MarkdownContent
            content={data.contentData}
            className={styles["giving__page-content"]}
          />

          <DynamicDonationForm />
        </Container>
      </div>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  const pageId = locale == "en" ? PagesIDs.Giving.en : PagesIDs.Giving.ru;

  const data = await RestApiService.getPageData(pageId);

  return {
    props: {
      data,
      ...(await serverSideTranslations(locale, ["common"])),
    },
    revalidate: 360,
  };
}
