import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import GreetingScreen from '@/ui/components/page-specific/home/GreetingScreen/GreetingScreen'
import RestApiService from '../services/RestApi';
import { PagesIDs } from '@/constants';

export default function Home({ data }: any) {
  const { 
    header_button_label, 
    header_descr, 
    header_h1_title
  } = data[0];

  return (
    <>
      <Head>
        <title>Bible Baptist Church</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <GreetingScreen
          header_h1_title={header_h1_title}
          header_descr={header_descr}
          header_button_label={header_button_label}
        />
      </>
    </>
  );
}

export async function getStaticProps({ locale }: any) {

  const pageId = (locale == 'en') ? PagesIDs.Home.en : PagesIDs.Home.ru;

  const data = await RestApiService.getPageData(pageId);

  return {
    props: {
      data,
      ...(await serverSideTranslations(locale, [
        'common',
      ])),
    },
    revalidate: 360,
  };
}
