import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import RestApiService from '@/services/RestApi';
import { YouTubePlaylistIDs } from '@/constants/EndpointsList';
import VideoStreamsList from '@/ui/components/page-specific/live-streams/VideoStreamsList/VideoStreamsList';
import Container from '@/ui/containers/Container/Container';

export default function Home({ streamsVideos }: any) {
  // console.log(streamsVideos)

  return (
    <>
      <Head>
        <title>Bible Baptist Church</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <VideoStreamsList data={streamsVideos} />
      </Container>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  const streamsVideos = await RestApiService.getYouTubePlaylistItems(YouTubePlaylistIDs.youthCamp2023Streams);

  return {
    props: {
      streamsVideos,
      ...(await serverSideTranslations(locale, [
        'common',
      ])),
    },
    revalidate: 60 * 30,
  };
}
