import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Container from "@/ui/containers/Container/Container";
import ContactUsForm from "@/ui/components/ContactUsForm/ContactUsForm";
import { WorshipParticipationRequestEndpoint } from "@/constants";
import StructuredMarkdownContent from "@/ui/components/StructuredMarkdownContent/StructuredMarkdownContent";
import Seo from "@/ui/components/Seo/Seo";
import Text from "@/ui/components/ui-kit/Text";
import PageContentDataApi from "@/services/PageMarkdownContentDataApi";
import { PagesIDs } from "@/constants";

import styles from '../styles/pages/participation.module.scss';


export default function ParticipationInWorship({ data }: any) {
  return (
    <>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Seo pageData={data} />
      
      <div className={styles.participation}>
        <Container isMarkdownContent>
          <Text textType="h1" className={styles.participation__title}>
            {data.title}
          </Text>

          <StructuredMarkdownContent
            content={data.pageContent}
            className={styles["participation__page-content"]}
          />

          <ContactUsForm
            API_URL={WorshipParticipationRequestEndpoint.dev}
            isContactWillingFieldExist={false}
          />
        </Container>
      </div>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  const pageId = locale == "en" ? PagesIDs.Participation.en : PagesIDs.Participation.ru;

  const data = await PageContentDataApi.getPageContentData(pageId);

  return {
    props: {
      data,
      ...(await serverSideTranslations(locale, ["common"])),
    },
    revalidate: 360,
  };
}
