import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Container from "@/ui/containers/Container/Container";
import StructuredMarkdownContent from "@/ui/components/StructuredMarkdownContent/StructuredMarkdownContent";
import { Text } from "@/ui/components/ui-kit";
import PageContentDataApi from "@/services/PageMarkdownContentDataApi";
import { PagesIDs } from "@/constants";

import styles from "../../styles/pages/upcoming-events.module.scss";

export default function UpcomingEvents({ pageData }: any) {
  return (
    <>
      <Head>
        <title>{pageData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles["upcoming-events"]}>
        <Container isMarkdownContent={true}>
          <Text textType="h1" className={styles["upcoming-events__title"]}>
            {pageData.title}
          </Text>
          
          <StructuredMarkdownContent
            content={pageData.pageContent}
            className={styles["upcoming-events__page-content"]}
          />
        </Container>
      </div>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  const pageId = locale == "en" ? PagesIDs.UpcomingEventsPage.en : PagesIDs.UpcomingEventsPage.ru;
  const pageData = await PageContentDataApi.getPageContentData(pageId);

  return {
    props: {
      pageData,
      ...(await serverSideTranslations(locale, ["common"])),
    },
    revalidate: 360,
  };
}
